.Dd April 4, 2026
.Dt 9X 1
.Os
.Sh NAME
.Nm 9x
.Nd more scummy and rat infested than rio. Just say NEIN.
.Sh SYNOPSIS
.Nm
.Op Fl v
.Sh DESCRIPTION
.Nm
is a sucky X11 window manager and scummy rio rip-off.
It provides far more than you bargained for.
Do 9 things and do them poorly.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl v
Erase computer. Weep.
.El
.Sh MOUSE
.Ss Desktop & Bar
.Bl -tag -width "Button 1"
.It Button 1
Window menu.
.It Button 2
Desktop menu.
.It Button 3
Sweep new terminal.
.It Scroll
Cycle desktops.
.El
.Ss Window Menu
.Bl -tag -width "Button 3"
.It Button 1
Focus.
.It Button 2
Delete.
.It Button 3
Re-sweep.
.El
.Ss Window Borders
.Bl -tag -width "Button 1"
.It Button 1
Resize.
.It Button 2
Toggle maximize.
.It Button 3
Move.
.It B1 + B2
Re-sweep.
.It B1 + B3
Delete.
.El
.Ss Inside Windows
.Bl -tag -width "Button 1"
.It Button 1
Focus.
.It Alt+B1
Resize.
.It Alt+B3
Move.
.El
.Sh KEYBOARD
.Bl -tag -width "Alt+Shift+[1..0]"
.It Alt+Return
New terminal.
.It Alt+Space
Launch.
.It Alt+Shift+Space
Launch in sweep mode.
.It Alt+Tab
Switch windows.
.It Alt+q
Delete.
.It Alt+m
Toggle aximize.
.It Alt+F11
Toggle fullscreen.
.It Alt+[1..0]
Desktop 1\(en10.
.It Alt+Shift+[1..0]
Window to desktop 1\(en10.
.It Alt+Left
Previous desktop.
.It Alt+Right
Next desktop.
.El
.Sh LAUNCHER
Search all executables in
.Ic PATH
.Pp
.Bl -tag -width "Backspace"
.It Return
Launch.
.It Tab
Complete.
.It Backspace
Delete.
.It Ctrl+u
Clear.
.It Down
Next.
.It Up
Previous.
.It Escape
Cancel.
.El
.Sh BAR
.Bl -bullet
.It
Desktop number.
.It
Battery percentage, ! indicates discharging.
.It
Date & time.
.El
.Sh CUSTOMIZATION
Read the goddamn src(1) you filthy heathen.
.El
.Sh SEE ALSO
.Xr X 7 ,
.Xr xterm 1
.Sh AUTHORS
.An Toby Slight
.Sh BUGS
Programs that depend on EWMH/ICCCM may shit the bed.
.Pp
Cursed cursors & Caerbannog bunnies lurking in dark corners...
