.Dd April 4, 2026
.Dt 9X 1
.Os
.Sh NAME
.Nm 9x
more scum & rats than rio. Just say NEIN.
.Sh DESCRIPTION
.Nm
is a scummy X11 window manager. A rat infested rio rip-off.
It provides far more than you bargained for.
Do 9 things and do them poorly.
.Sh OPTIONS
.Bl -tag -width "-v"
.It Fl v
Erase computer. Weep.
.El
.Sh MOUSE
.Ss Run Button
.Bl -tag -width "Hover"
.It Hover
Run launcher.
.El
.Ss Launcher
.Bl -tag -width "Button 3"
.It Button 1
Launch.
.It Button 3
Sweep.
.El
.Ss Window Tabs
.Bl -tag -width "Button 1"
.It Hover
Focus.
.It Button 1
Maximize.
.It Button 2
Delete.
.It Button 3
Re-Sweep.
.El
.Ss Desktop Buttons
.Bl -tag -width "Button 3"
.It Button 1
Switch.
.It Button 2
Send window (stay).
.It Button 3
Send window (follow).
.El
.Ss Status Area (Battery/Clock)
.Bl -tag -width "Any Button"
.It "Any Button"
Sweep.
.El
.Ss Window Borders
.Bl -tag -width "Doubleclick"
.It Button 1
Resize.
.It Button 2
Delete.
.It Button 3
Move.
.It Doubleclick
Tile side or corner.
.El
.Ss Root Window
.Bl -tag -width "Any Button"
.It "Any Button"
Sweep.
.El
.Sh KEYBOARD
.Bl -tag -width "Fullscreen"
.It MOD+F11
Fullscreen.
.El
.Sh CUSTOMIZATION
Read the goddamn src(1) you filthy heathen.
.El
.Sh SEE ALSO
.Xr X 7 ,
.Xr xterm 1
.Sh AUTHORS
.An Toby Slight
.Sh BUGS
Programs that depend on EWMH/ICCCM may shit the bed.
.Pp
Cursed cursors & Caerbannog bunnies lurking in dark corners...
